<template>
  <section class="admin-ticket-page">
    <div class="page-heading"><div><span>PROBLEM OPERATIONS</span><h2>工单管理</h2><p>核对影响范围，由管理员上传完整题包后执行。</p></div><div><el-button @click="router.push('/admin/author-permissions')">出题资格管理</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div>
    <section class="summary-grid"><article><span>待处理</span><strong>{{ count('pending') }}</strong></article><article><span>处理中</span><strong>{{ count('processing') }}</strong></article><article><span>本页已完成</span><strong>{{ count('completed') }}</strong></article></section>
    <section class="panel ticket-panel">
      <div class="filters"><el-select v-model="statusFilter"><el-option label="全部状态" value=""/><el-option label="待处理" value="pending"/><el-option label="处理中" value="processing"/><el-option label="已完成" value="completed"/><el-option label="已驳回" value="rejected"/><el-option label="已取消" value="cancelled"/></el-select></div>
      <el-table v-loading="loading" :data="filtered" row-key="id">
        <el-table-column label="工单" width="85"><template #default="{row}">#{{row.id}}</template></el-table-column><el-table-column label="类型" width="85"><template #default="{row}">{{actionLabel(row.action)}}</template></el-table-column><el-table-column label="申请人" width="130"><template #default="{row}">{{row.requester?.name || `#${row.requester_id}`}}</template></el-table-column><el-table-column label="目标" min-width="190"><template #default="{row}">{{row.problem ? `${row.problem.display_code || row.problem.id} · ${row.problem.title}` : '新题目'}}</template></el-table-column><el-table-column prop="description" label="说明" min-width="250" show-overflow-tooltip/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column label="提交时间" width="170"><template #default="{row}">{{formatDateTime(row.created_at)}}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-button link type="primary" @click="open(row)">查看</el-button></template></el-table-column>
      </el-table>
    </section>
    <el-drawer v-model="drawer" title="工单处理" size="min(560px, 100%)">
      <template v-if="active"><div class="ticket-detail"><el-descriptions :column="1" border><el-descriptions-item label="工单">#{{active.id}} · {{actionLabel(active.action)}}</el-descriptions-item><el-descriptions-item label="申请人">{{active.requester?.name}}（{{active.requester?.email}}）</el-descriptions-item><el-descriptions-item label="目标题目">{{active.problem?.title || '新建题目'}}</el-descriptions-item><el-descriptions-item label="说明">{{active.description}}</el-descriptions-item><el-descriptions-item label="参考附件"><el-button v-if="active.attachment_name" link type="primary" @click="downloadAttachment(active)">{{active.attachment_name}}</el-button><span v-else>无</span></el-descriptions-item></el-descriptions>
        <section v-if="active.impact_summary" class="impact-card"><h3>影响范围</h3><div><span>未开始考试<strong>{{active.impact_summary.future_exams}}</strong></span><span>已固定考试<strong>{{active.impact_summary.pinned_exams}}</strong></span><span>未开始比赛<strong>{{active.impact_summary.future_contests}}</strong></span><span>已固定比赛<strong>{{active.impact_summary.pinned_contests}}</strong></span><span>历史提交<strong>{{active.impact_summary.historical_submissions}}</strong></span></div><p>执行替换后，仅未开始场次切换到新版本；已开始场次与历史提交继续使用原版本。</p></section>
        <template v-if="active.status === 'pending'"><el-form label-position="top"><el-form-item v-if="active.action !== 'archive'" label="完整最终题包" required><el-upload :auto-upload="false" :limit="1" accept=".zip" :on-change="pickPackage" :on-remove="clearPackage"><el-button>选择 ZIP 题包</el-button></el-upload></el-form-item><el-form-item v-if="active.action !== 'archive'" label="难度"><el-select v-model="applyForm.difficulty" clearable><el-option v-for="v in difficulties" :key="v" :label="v" :value="v"/></el-select></el-form-item><el-form-item label="处理说明"><el-input v-model="applyForm.note" type="textarea" :rows="4"/></el-form-item></el-form><div class="drawer-actions"><el-button type="danger" plain @click="reject">驳回</el-button><el-button type="primary" :loading="applying" @click="apply">{{active.action === 'archive' ? '确认归档' : '上传并执行'}}</el-button></div></template><el-alert v-else :title="`工单${statusLabel(active.status)}`" :description="active.resolution_note || '暂无处理说明'" :type="active.status === 'completed' ? 'success' : 'info'" :closable="false"/></div></template>
    </el-drawer>
  </section>
</template>
<script setup lang="ts">
import { ElMessage, ElMessageBox } from 'element-plus'; import { computed,onMounted,reactive,ref } from 'vue'; import { useRouter } from 'vue-router'; import { client,type ProblemChangeAction,type ProblemChangeStatus,type ProblemChangeTicket } from '../../api/client'; import { problemDifficultyOptions } from '../../features/problems/problemMeta'; import { formatDateTime } from '../../features/time';
const router=useRouter(),loading=ref(false),applying=ref(false),drawer=ref(false),tickets=ref<ProblemChangeTicket[]>([]),active=ref<ProblemChangeTicket|null>(null),statusFilter=ref('pending'),packageFile=ref<File|null>(null),difficulties=problemDifficultyOptions; const applyForm=reactive({difficulty:'',note:''}); const filtered=computed(()=>statusFilter.value?tickets.value.filter(i=>i.status===statusFilter.value):tickets.value)
async function load(){loading.value=true;try{tickets.value=(await client.get<ProblemChangeTicket[]>('/problem-change-tickets')).data||[]}catch(e:any){ElMessage.error(e.response?.data?.error||e.message)}finally{loading.value=false}}
async function open(row:ProblemChangeTicket){active.value=row;packageFile.value=null;Object.assign(applyForm,{difficulty:row.problem?.difficulty||'',note:''});drawer.value=true;try{active.value=(await client.get<ProblemChangeTicket>(`/problem-change-tickets/${row.id}`)).data}catch(e:any){ElMessage.error(e.response?.data?.error||e.message)}} function pickPackage(file:{raw?:File}){packageFile.value=file.raw||null} function clearPackage(){packageFile.value=null}
async function apply(){if(!active.value)return;if(active.value.action!=='archive'&&!packageFile.value)return ElMessage.warning('请上传完整最终题包');applying.value=true;try{const data=new FormData();if(packageFile.value)data.append('package',packageFile.value);data.append('difficulty',applyForm.difficulty);data.append('resolution_note',applyForm.note.trim());await client.post(`/problem-change-tickets/${active.value.id}/apply`,data);ElMessage.success('工单已执行并生成题目版本');drawer.value=false;await load()}catch(e:any){ElMessage.error(e.response?.data?.error||e.message)}finally{applying.value=false}}
async function reject(){if(!active.value)return;try{const note=await ElMessageBox.prompt('填写驳回原因','驳回工单',{inputType:'textarea',inputValidator:(v)=>Boolean(v.trim())||'必须填写原因'});await client.post(`/problem-change-tickets/${active.value.id}/reject`,{note:note.value.trim()});drawer.value=false;await load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.response?.data?.error||e.message)}}
function count(s:ProblemChangeStatus){return tickets.value.filter(i=>i.status===s).length} function actionLabel(v:ProblemChangeAction){return v==='create'?'新增':v==='replace'?'替换':'删除'} function statusLabel(v:ProblemChangeStatus){return({pending:'待处理',processing:'处理中',completed:'已完成',rejected:'已驳回',cancelled:'已取消'}as const)[v]} function statusType(v:ProblemChangeStatus):'success'|'warning'|'danger'|'info'{return v==='completed'?'success':v==='pending'||v==='processing'?'warning':v==='rejected'?'danger':'info'} async function downloadAttachment(row:ProblemChangeTicket){try{const response=await client.get(`/problem-change-tickets/${row.id}/attachment`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const anchor=document.createElement('a');anchor.href=url;anchor.download=row.attachment_name||`ticket-${row.id}-attachment`;anchor.click();URL.revokeObjectURL(url)}catch(e:any){ElMessage.error(e.response?.data?.error||e.message)}}
onMounted(load)
</script>
<style scoped>.admin-ticket-page{padding:28px}.page-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:18px}.page-heading>div:last-child{display:flex;gap:8px}.page-heading span{color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.14em}.page-heading h2{margin:6px 0}.page-heading p{margin:0;color:var(--muted)}.summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:14px}.summary-grid article{padding:18px;border:1px solid var(--border);border-radius:8px;background:var(--surface-strong)}.summary-grid span,.summary-grid strong{display:block}.summary-grid span{color:var(--muted)}.summary-grid strong{margin-top:5px;font-size:26px}.ticket-panel{padding:16px}.filters{display:flex;justify-content:flex-end;margin-bottom:12px}.ticket-detail{display:grid;gap:18px}.impact-card{padding:15px;border:1px solid var(--border);border-radius:8px;background:var(--surface)}.impact-card h3{margin:0 0 12px}.impact-card>div{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.impact-card span{padding:9px;color:var(--muted);border-radius:6px;background:var(--surface-strong)}.impact-card strong{display:block;margin-top:3px;color:var(--text);font-size:18px}.impact-card p{margin:10px 0 0;color:var(--muted);font-size:12px;line-height:1.6}.file-input{width:100%;padding:11px;border:1px dashed var(--border);border-radius:7px}.drawer-actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:720px){.admin-ticket-page{padding:18px 12px}.page-heading{align-items:stretch;flex-direction:column}.summary-grid{grid-template-columns:1fr}.impact-card>div{grid-template-columns:repeat(2,1fr)}}</style>
